# -*- coding: utf-8 -*-
"""tictactoe.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r4PmlTYokcw2fEYyMEdsMi4mOTh_gG8p
"""

#stage1 creating tic tac toe board display

theBoard = ["-", "-", "-",
        "-", "-", "-",
        "-", "-", "-"]

currentPlayer = "X"

gamePlaying = True

def print_board(theBoard):
    print(theBoard[0] + " | " + theBoard[1] + " | " + theBoard[2])
    print("---------")
    print(theBoard[3] + " | " + theBoard[4] + " | " + theBoard[5])
    print("---------")
    print(theBoard[6] + " | " + theBoard[7] + " | " + theBoard[8])
print_board(theBoard)



#stage 2 take marks from players one and two

def playerInput(theBoard):
  turn = (int(input("Enter a number 1-9: ")))
  if turn >= 1 and turn <= 9 and theBoard[turn-1] == "-":
    theBoard[turn-1] = currentPlayer
  else:
    print("Choose another spot this one is not available")


while gamePlaying:
  print_board(theBoard)
  playerInput(theBoard)